CREATE TABLE IF NOT EXISTS CUSTOMER(
    ID_CUSTOMER BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    CPF VARCHAR(11),
    DELETED BIT(1)
)ENGINE InnoDB DEFAULT CHARSET=UTF8;