CREATE TABLE ACCOUNT(
    ID_ACCOUNT BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BALANCE DECIMAL(10, 2) DEFAULT 0,
    RF_CUSTOMER BIGINT(20) NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    NUMBER_ACCOUNT BIGINT(10) NOT NULL,
    AGENCY VARCHAR(20) NOT NULL,
    DELETED BIT(1),
    FOREIGN KEY (RF_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER)
)ENGINE InnoDB DEFAULT CHARSET=UTF8;