CREATE TABLE BANK_TRANSACTION(
    ID_TRANSACTION BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DATE_TRANSACTION TIMESTAMP NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT_SENT DECIMAL(10, 2) NOT NULL,
    RF_ACCOUNT_SPONSOR BIGINT(20) NOT NULL,
    RF_ACCOUNT_DESTINY BIGINT(20) NOT NULL,
    FOREIGN KEY (RF_ACCOUNT_SPONSOR) REFERENCES ACCOUNT(ID_ACCOUNT),
    FOREIGN KEY (RF_ACCOUNT_DESTINY) REFERENCES ACCOUNT(ID_ACCOUNT)
)ENGINE InnoDB DEFAULT CHARSET=UTF8;