INSERT INTO ACCOUNT (ID_ACCOUNT, BALANCE, RF_CUSTOMER, ACCOUNT_TYPE, NUMBER_ACCOUNT, AGENCY, DELETED)
VALUES (NULL, 50.0, 1, 'CONTA_POUPANCA', '23659', '222', 0);

INSERT INTO ACCOUNT (ID_ACCOUNT, BALANCE, RF_CUSTOMER, ACCOUNT_TYPE, NUMBER_ACCOUNT, AGENCY, DELETED)
VALUES (NULL, 50.0, 2, 'CONTA_POUPANCA', '123456', '222', 0);