INSERT INTO CUSTOMER (ID_CUSTOMER, FIRSTNAME, LASTNAME, CPF, DELETED)
VALUES (NULL, 'Nikola', 'Jokic', '31838835547', 0);

INSERT INTO CUSTOMER (ID_CUSTOMER, FIRSTNAME, LASTNAME, CPF, DELETED)
VALUES (NULL, 'Otto', 'Porter Junior', '55423476577', 0);